### ISSUE TITLE
Seminars as events

### ISSUE THREAD

**Issue by mrigger** [nus-test/nus-test.github.io#43]
It seems that our template allows specifying "events" (see https://research-group.netlify.app/event/ and https://github.com/wowchemy/starter-hugo-research-group/tree/main/content/event). This might be more flexible than a table (e.g., I think it would be better to show the latest and upcoming talks first, and we could automatically sort the talks by using events)? cc @bajinsheng

**Comment by bajinsheng** [comment]
The event tab requires too much information, a large portion of it is not necessary I think. And also it would take a longer time to maintain it. Also, the events cannot be sorted. Have not found a solution about how to customize it.
I am not sure it is worth spending so much time maintaining the seminar information.

**Comment by bajinsheng** [comment]
Merged #44.

**Comment by mrigger** [comment]
Great, thanks! I think we could still leave the "seminar" name, which is more specific than "events". It seems also your update in https://github.com/nus-test/nus-test.github.io/pull/42 got lost?

**Comment by bajinsheng** [comment]
Completed by #46
